language: python
python:
  - "3.4"
  - "3.5"

matrix:
  allow_failures:
    - "2.7"

# command to install dependencies
install:
    - python setup.py install
    - pip install coveralls

# command to run tests
script:
    - coverage run --source=archives_org_latin_toolkit setup.py test

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then coveralls; fi

branches:
  only:
    - master